import { DEFAULT_SLIDE_APPEARANCE } from "@/lib/slide-appearance";
import type { PitchTemplate } from "@/types/template";
import type { Slide, SlideContent, SlideType } from "@/types/slide";
import type { IntakeFormData } from "@/types/workflow";

function imagePromptForSlideType(
  slideType: SlideType,
  form: IntakeFormData,
): string | undefined {
  const title = form.title.trim();
  const mood = (form.visualAesthetic || form.tone || "cinematic").trim();
  const visualTypes: SlideType[] = [
    "cover",
    "logline",
    "genre_blend",
    "synopsis",
    "story_world",
    "character",
    "supporting_characters",
    "visual_aesthetic",
    "show_cross",
  ];
  if (!visualTypes.includes(slideType)) return undefined;

  const label = title || "the project";
  switch (slideType) {
    case "cover":
      return `Cinematic title slide for "${label}", ${mood} atmosphere.`;
    case "visual_aesthetic":
      return `Mood board collage: ${mood}.`;
    case "story_world":
      return `Story world visual for "${label}": ${form.storyWorld?.slice(0, 80) || mood}.`;
    default:
      return `Pitch deck slide imagery for "${label}", ${mood}, ${slideType} slide.`;
  }
}

export function contentForSlideType(
  slideType: SlideType,
  form: IntakeFormData,
): SlideContent {
  // Everything below derives from the user's OWN intake — no hardcoded story content. Empty fields
  // yield empty content; the backend content agent writes the real copy at generation time.
  const split = (text: string, re: RegExp, limit: number) =>
    text.split(re).map((s) => s.trim()).filter(Boolean).slice(0, limit);
  const joined = (...xs: string[]) => xs.map((s) => s.trim()).filter(Boolean);

  switch (slideType) {
    case "cover": {
      const synopsisLead = form.synopsis.trim().split(/\n/)[0]?.trim() ?? "";
      return {
        heading: form.title.toUpperCase() || "UNTITLED",
        subheading: form.tagline,
        body: form.logline.trim() || synopsisLead,
        footer: "",
      };
    }
    case "logline":
      return { heading: "Logline", body: form.logline };
    case "genre_blend": {
      const genres = split(form.genreBlend, /[+,&]/, 3);
      return {
        heading: "Genre Blend",
        items: genres.map((title) => ({
          title,
          description: form.tone || (form.title ? `${title} in ${form.title}` : title),
        })),
      };
    }
    case "synopsis":
      return { heading: "Synopsis", body: form.synopsis };
    case "story_world":
      return { heading: "Story World", body: form.storyWorld };
    case "character":
    case "supporting_characters": {
      const source =
        slideType === "supporting_characters"
          ? form.supportingCharacters || form.mainCharacters
          : form.mainCharacters;
      return {
        heading: slideType === "character" ? "Main Characters" : "Supporting Characters",
        characters: split(source, /[.;]/, 6).map((line) => {
          const parts = line.split("—").map((p) => p.trim());
          return {
            name: parts[0] || "Character",
            role: parts[1] || "",
            description: parts[2] || form.characterDynamics || "",
          };
        }),
      };
    }
    case "relationship_map":
      return {
        heading: "Relationship Map",
        characters: split(form.mainCharacters, /[.;]/, 6).map((line) => {
          const parts = line.split("—").map((p) => p.trim());
          return { name: parts[0] || "Character", role: parts[1] || "", description: parts[2] || "" };
        }),
        relationships: [],
      };
    case "usp":
      return { heading: "Unique Selling Points", bullets: split(form.usp, /[.;]/, 5) };
    case "show_cross":
      return {
        heading: "Show Cross",
        comps: split(form.showCross, /[,×x]/, 3).map((title) => ({
          title,
          note: form.targetAudience,
        })),
      };
    case "visual_aesthetic":
      return {
        heading: "Visual Aesthetic",
        body: form.visualAesthetic || form.designDirection,
        // Reference-film mood tiles are generated by the backend — nothing hardcoded here.
        moodBlocks: [],
      };
    case "target_audience":
      return {
        heading: "Target Audience",
        items: [
          { title: "Audience", description: form.targetAudience },
          { title: "Release", description: form.releaseFit },
        ].filter((it) => it.description.trim()),
      };
    case "budget":
      return { heading: "Budget & Production Scale", body: form.budget };
    case "market_potential":
      return {
        heading: "Market Potential",
        items: [
          { title: "Release Fit", description: form.releaseFit },
          { title: "Distribution", description: form.distribution },
          { title: "Why Now", description: form.whyNow },
        ].filter((it) => it.description.trim()),
      };
    case "directors_vision":
      return {
        heading: "Director's Vision",
        body: form.directorVision || form.directorStatement || form.designDirection,
      };
    case "team":
      return {
        heading: "Team & Production Status",
        body: joined(form.creativeTeam, form.productionStatus).join(" · "),
      };
    case "contact":
      return {
        heading: "Let's Talk",
        subheading: form.title ? `${form.title} — Pitch Deck` : "Pitch Deck",
        body: form.releaseFit.trim(),
        footer: "",
      };
    default:
      return { heading: "Slide", body: form.synopsis };
  }
}

export function buildSlidesFromTemplate(
  template: PitchTemplate,
  form: IntakeFormData,
): Slide[] {
  const enrichedForm: IntakeFormData = {
    ...form,
    visualAesthetic:
      form.visualAesthetic || template.designDirection.visualStyle.join(", "),
    designDirection: template.designDirection.rationale,
  };

  return template.slideOutline.map((outline, index) =>
    buildSlideFromOutline(outline, enrichedForm, index + 1),
  );
}

export function buildSlideFromOutline(
  outline: {
    slideType: SlideType;
    title: string;
    purpose: string;
  },
  form: IntakeFormData,
  slideNumber: number,
  id?: string,
): Slide {
  const layoutTypes: Partial<Record<SlideType, string>> = {
    cover: "cinematic_cover",
    logline: "centered_statement",
    genre_blend: "three_column",
    synopsis: "split_image_text",
    story_world: "location_grid",
    character: "character_cards",
    usp: "grid",
    show_cross: "comp_cards",
    visual_aesthetic: "moodboard",
    target_audience: "segments",
    market_potential: "investor_cards",
    contact: "minimal",
  };

  return {
    id: id ?? `slide-${slideNumber}-${outline.slideType}-${Date.now()}`,
    slideNumber,
    slideType: outline.slideType,
    title: outline.title,
    purpose: outline.purpose,
    content: contentForSlideType(outline.slideType, form),
    layout: {
      template: outline.slideType,
      layoutType: layoutTypes[outline.slideType] ?? "auto",
    },
    status: "design_generated",
    imagePrompt: imagePromptForSlideType(outline.slideType, form),
    appearance: { ...DEFAULT_SLIDE_APPEARANCE },
    speakerNotes: "",
    comments: [],
    transition: "Fade",
  };
}

export function renumberSlides(slides: Slide[]): Slide[] {
  return slides.map((s, i) => ({ ...s, slideNumber: i + 1 }));
}
